# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rxswift-learning' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rxswift-learning
  pod 'SnapKit', '~> 4.0.0'
  pod 'Money-FlightSchool'
  pod 'UMCSecurityPlugins'
  pod 'RxSwift', '~> 5.0.0'
  pod 'RxCocoa'
  pod 'MJRefresh'
  pod 'RxDataSources', '~> 4.0.1'
  pod 'ObjectMapper', '~> 3.5.1'
  pod 'Moya'
  pod 'Result'
  pod 'Alamofire'
end
